# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-28 19:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Binary',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=300)),
                ('path', models.CharField(max_length=500)),
                ('notes', models.CharField(default='*No Notes Provided*', max_length=2000)),
                ('status', models.CharField(max_length=20)),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('status_change_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, unique=True)),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='binary',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='releases.Product'),
        ),
    ]
