# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-28 19:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('releases', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='upload_date',
            new_name='create_date',
        ),
    ]
