# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-28 22:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('releases', '0004_auto_20160628_2004'),
    ]

    operations = [
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, unique=True)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('path', models.CharField(default='tmp/', max_length=500)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='releases.Product')),
            ],
        ),
        migrations.RemoveField(
            model_name='binary',
            name='product',
        ),
        migrations.AddField(
            model_name='binary',
            name='component',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='releases.Component'),
        ),
    ]
