# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-29 21:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('releases', '0005_auto_20160628_2242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='binary',
            name='path',
            field=models.FilePathField(),
        ),
    ]
