# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-29 22:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('releases', '0006_auto_20160629_2143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='binary',
            name='path',
            field=models.FileField(upload_to='binaries/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='binary',
            name='status',
            field=models.CharField(default='New', max_length=20),
        ),
    ]
