# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-30 17:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('releases', '0007_auto_20160629_2248'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='component',
            name='path',
        ),
        migrations.RemoveField(
            model_name='product',
            name='path',
        ),
        migrations.AlterField(
            model_name='binary',
            name='path',
            field=models.FilePathField(),
        ),
    ]
