# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-01 19:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('releases', '0008_auto_20160630_1716'),
    ]

    operations = [
        migrations.AddField(
            model_name='binary',
            name='url',
            field=models.CharField(default='#', max_length=1000),
        ),
    ]
